# Basic Formatting Information
theme: jekyll-slate
title: Simple Classroom RPG
description: A simple 3d6 roleplaying game for the college classroom. Hopes to build micro-cohorts, promote critical thinking, and tackle important content-specific concepts.

layout: page
title: License
permalink: /cc/
